### PR TITLE
Corrected page titles

### PR DESCRIPTION
**Pull request by MichaelChan-Pong**
I noticed that the page titles for some pages said UFPT instead of what they actually were, so I made some small changes :)
Also the "Contact Us" title was inconsistent with all the others so I changed that too.

### CODE REVIEW

**Comment by andrewjkerr** [comment]
This looks great, thanks for the submission!

Small nit: can you change the titles to be "[page] | UF ACM" and only make the first letter of each work capitalized? For example, "Change Password | UF ACM".

**Comment by MichaelChan-Pong** [comment]
@andrewjkerr Sure, I personally thought the titles were a bit shouty myself, but I just followed the convention already set. I'll have the fixes done in a minute!

**Comment by MichaelChan-Pong** [comment]
Also, @progdude check your phone lol

**Comment by andrewjkerr** [comment]
No worries; thanks again for the PR! :)

**Pull request merged**
